import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, HeadingLevel, BorderStyle, WidthType, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

/**
 * Validate workout object has required structure
 */
const validateWorkout = (workout) => {
  if (!workout || typeof workout !== 'object') return false;
  if (!workout.title || typeof workout.title !== 'string') return false;
  if (!Array.isArray(workout.blocks)) return false;
  return true;
};

/**
 * Safely format a date string from workout data
 */
const getDateStr = (workout) => {
  try {
    return workout.date ? new Date(workout.date).toLocaleDateString() : new Date().toLocaleDateString();
  } catch {
    return new Date().toLocaleDateString();
  }
};

/**
 * Safely create a sanitized filename
 */
const sanitizeFilename = (title, dateStr, ext) => {
  const safeName = (title || 'workout').replace(/[^a-z0-9]/gi, '_').substring(0, 50);
  const safeDate = (dateStr || '').replace(/\//g, '-');
  return `${safeName}_${safeDate}.${ext}`;
};

/**
 * Export workout to PDF
 */
export const exportToPDF = (workout) => {
  if (!validateWorkout(workout)) {
    throw new Error('Invalid workout data for PDF export.');
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(139, 0, 0); // Marine red
  doc.rect(0, 0, pageWidth, 25, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('MarineFit', 14, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('HITT WORKOUT CARD', pageWidth - 14, 16, { align: 'right' });

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(workout.title, 14, 38);

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const dateStr = getDateStr(workout);
  doc.text(`Date: ${dateStr}`, 14, 46);

  let yPos = 56;

  // Blocks
  workout.blocks.forEach((block, blockIndex) => {
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    // Block header
    doc.setFillColor(139, 0, 0);
    doc.rect(14, yPos - 5, 3, 8, 'F');
    doc.setTextColor(139, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(block.name.toUpperCase(), 20, yPos);
    yPos += 8;

    // Exercises table
    const tableData = block.exercises.map((ex, idx) => {
      const prescription = ex.prescription || {};
      const setsReps = prescription.sets && prescription.reps
        ? `${prescription.sets} x ${prescription.reps}`
        : '-';
      const rest = prescription.rest || '-';
      const notes = prescription.notes || '';

      return [
        (idx + 1).toString(),
        ex.name,
        ex.equipment || 'Bodyweight',
        setsReps,
        rest,
        notes
      ];
    });

    if (tableData.length > 0) {
      doc.autoTable({
        startY: yPos,
        head: [['#', 'Exercise', 'Equipment', 'Sets x Reps', 'Rest', 'Notes']],
        body: tableData,
        margin: { left: 14, right: 14 },
        styles: {
          fontSize: 9,
          cellPadding: 3
        },
        headStyles: {
          fillColor: [70, 70, 70],
          textColor: [255, 255, 255],
          fontStyle: 'bold'
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245]
        },
        columnStyles: {
          0: { cellWidth: 10 },
          1: { cellWidth: 45 },
          2: { cellWidth: 30 },
          3: { cellWidth: 25 },
          4: { cellWidth: 20 },
          5: { cellWidth: 'auto' }
        }
      });

      yPos = doc.lastAutoTable.finalY + 12;
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by MarineFit - COMBAT FIT. COMBAT READY.',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save
  const fileName = sanitizeFilename(workout.title, dateStr, 'pdf');
  doc.save(fileName);
};

/**
 * Export workout to Excel
 */
export const exportToExcel = (workout) => {
  if (!validateWorkout(workout)) {
    throw new Error('Invalid workout data for Excel export.');
  }

  const workbook = XLSX.utils.book_new();

  // Summary sheet
  const summaryData = [
    ['MarineFit Workout Card'],
    [''],
    ['Title:', workout.title],
    ['Date:', getDateStr(workout)],
    ['Total Blocks:', workout.blocks.length],
    ['Total Exercises:', workout.blocks.reduce((sum, b) => sum + b.exercises.length, 0)],
    [''],
    ['COMBAT FIT. COMBAT READY.']
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  summarySheet['!cols'] = [{ wch: 15 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Full workout sheet
  const workoutData = [
    ['#', 'Block', 'Exercise', 'Equipment', 'Sets', 'Reps', 'Rest', 'Notes']
  ];

  let exerciseNum = 1;
  workout.blocks.forEach((block) => {
    block.exercises.forEach((ex) => {
      const prescription = ex.prescription || {};
      workoutData.push([
        exerciseNum++,
        block.name,
        ex.name,
        ex.equipment || 'Bodyweight',
        prescription.sets || '',
        prescription.reps || '',
        prescription.rest || '',
        prescription.notes || ''
      ]);
    });
  });

  const workoutSheet = XLSX.utils.aoa_to_sheet(workoutData);
  workoutSheet['!cols'] = [
    { wch: 5 },
    { wch: 20 },
    { wch: 35 },
    { wch: 15 },
    { wch: 8 },
    { wch: 10 },
    { wch: 10 },
    { wch: 30 }
  ];
  XLSX.utils.book_append_sheet(workbook, workoutSheet, 'Workout');

  // Individual block sheets
  workout.blocks.forEach((block, idx) => {
    const blockData = [
      ['#', 'Exercise', 'Equipment', 'Sets', 'Reps', 'Rest', 'Notes']
    ];

    block.exercises.forEach((ex, exIdx) => {
      const prescription = ex.prescription || {};
      blockData.push([
        exIdx + 1,
        ex.name,
        ex.equipment || 'Bodyweight',
        prescription.sets || '',
        prescription.reps || '',
        prescription.rest || '',
        prescription.notes || ''
      ]);
    });

    const blockSheet = XLSX.utils.aoa_to_sheet(blockData);
    blockSheet['!cols'] = [
      { wch: 5 },
      { wch: 35 },
      { wch: 15 },
      { wch: 8 },
      { wch: 10 },
      { wch: 10 },
      { wch: 30 }
    ];

    // Truncate sheet name to 31 chars (Excel limit)
    const sheetName = block.name.substring(0, 31);
    XLSX.utils.book_append_sheet(workbook, blockSheet, sheetName);
  });

  // Save
  const dateStr = getDateStr(workout);
  const fileName = sanitizeFilename(workout.title, dateStr, 'xlsx');
  XLSX.writeFile(workbook, fileName);
};

/**
 * Export workout to Word document
 */
export const exportToWord = async (workout) => {
  if (!validateWorkout(workout)) {
    throw new Error('Invalid workout data for Word export.');
  }

  const dateStr = getDateStr(workout);

  // Build document sections
  const children = [
    // Header
    new Paragraph({
      children: [
        new TextRun({
          text: 'MarineFit',
          bold: true,
          size: 36,
          color: '8B0000'
        }),
        new TextRun({
          text: '  |  HITT WORKOUT CARD',
          size: 24,
          color: '666666'
        })
      ],
      spacing: { after: 200 }
    }),

    // Title
    new Paragraph({
      children: [
        new TextRun({
          text: workout.title,
          bold: true,
          size: 32
        })
      ],
      spacing: { after: 100 }
    }),

    // Date
    new Paragraph({
      children: [
        new TextRun({
          text: `Date: ${dateStr}`,
          size: 20,
          color: '666666'
        })
      ],
      spacing: { after: 300 }
    })
  ];

  // Add blocks
  workout.blocks.forEach((block) => {
    // Block header
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: block.name.toUpperCase(),
            bold: true,
            size: 24,
            color: '8B0000'
          })
        ],
        spacing: { before: 300, after: 150 },
        border: {
          left: {
            color: '8B0000',
            size: 24,
            style: BorderStyle.SINGLE,
            space: 10
          }
        }
      })
    );

    // Exercises table
    if (block.exercises.length > 0) {
      const tableRows = [
        // Header row
        new TableRow({
          tableHeader: true,
          children: ['#', 'Exercise', 'Equipment', 'Sets x Reps', 'Rest', 'Notes'].map(text =>
            new TableCell({
              children: [new Paragraph({
                children: [new TextRun({ text, bold: true, size: 20, color: 'FFFFFF' })]
              })],
              shading: { fill: '464646' },
              width: { size: text === 'Exercise' ? 30 : text === 'Notes' ? 20 : 10, type: WidthType.PERCENTAGE }
            })
          )
        })
      ];

      // Data rows
      block.exercises.forEach((ex, idx) => {
        const prescription = ex.prescription || {};
        const setsReps = prescription.sets && prescription.reps
          ? `${prescription.sets} x ${prescription.reps}`
          : '-';

        const rowData = [
          (idx + 1).toString(),
          ex.name,
          ex.equipment || 'Bodyweight',
          setsReps,
          prescription.rest || '-',
          prescription.notes || ''
        ];

        tableRows.push(
          new TableRow({
            children: rowData.map((text, colIdx) =>
              new TableCell({
                children: [new Paragraph({
                  children: [new TextRun({ text, size: 20 })]
                })],
                shading: { fill: idx % 2 === 0 ? 'FFFFFF' : 'F5F5F5' },
                width: { size: colIdx === 1 ? 30 : colIdx === 5 ? 20 : 10, type: WidthType.PERCENTAGE }
              })
            )
          })
        );
      });

      children.push(
        new Table({
          rows: tableRows,
          width: { size: 100, type: WidthType.PERCENTAGE }
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: 'No exercises in this block.',
              italics: true,
              color: '999999'
            })
          ]
        })
      );
    }
  });

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by MarineFit - COMBAT FIT. COMBAT READY.',
          size: 16,
          color: '999999'
        })
      ],
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER
    })
  );

  const doc = new Document({
    sections: [{
      properties: {},
      children
    }]
  });

  // Generate and save
  const blob = await Packer.toBlob(doc);
  const fileName = sanitizeFilename(workout.title, dateStr, 'docx');
  saveAs(blob, fileName);
};
